openapi: 3.0.0
info:
  title: Quote of the Day
  description:
    A service that display a quote.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local quote server
paths:
  /quote:
    get:
      summary: Deliver a quote randomly
      #requestBody is not required
      responses:
        '200':
          description: A quote object
          content:
            application/json:
              schema:
                type: string
                items:
                  $ref: '#/components/schemas/Quote'
                  #the response will come as a json file
    #Quote schemas is according to the class/model Quote which has 2 properties
components:
  schemas:
    Quote:
      properties:
        Author:
          type: string
        quotes:
          type: string
        