openapi: 3.0.0
info:
  title: Word and the Definition
  description:
    A service that display a word with it's definition.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local word server
paths:
  /word:
    get:
      summary: Deliver a word and the definition randomly
      #requestBody is not required
      responses:
        '200':
          description: A definition object
          content:
            application/json:
              schema:
                type: string
                items:
                  $ref: '#/components/schemas/Definition'
                  #the response will come as a json file
         #schemas Definition is according to the model with its properties
components:
  schemas:
    Definition:
      properties:
        word:
          type: string
        definition:
          type: string
        